### ISSUE TITLE
Lots of clicking on newest binary (RPi 3)

### ISSUE THREAD

**Issue by nikkoman** [libretro/snes9x2010#101]
It seems that the artefact issue on Hook (USA) has just been fixed but now I get lots of clicking noises on Hook and several other games. 

I also tried updating from source and there's no difference, same sound (slowdown?) issue.

Reverted to the previous core binary e3b7fa5 and everything sounds normal.

**Comment by nikkoman** [comment]
I experimented again,  most games suffer from this. Earthworm Jim's clicks are extremely distracting. It seems that either the Hook (USA) fix or the new Star Fox 2 hack cause some sync issue. Verified on my second RPi 3 (all non-OC).

**Comment by nikkoman** [comment]
Apparently no, e3b7fa5 doesn't solve this. Actually it seems to date back a lot!

What's really strange here is that lr-snes9x now has far less crackling issues on most non-FX chip games (which lr-snes2010 does in a lower degree).

Since 2010 is supposed to be more effecient, I don't understand why the lr-snes9x variant feels much faster.

I even enabled rewind and the CRT shader... snes9x2010 suffers terribly (try Earthworm Jim for a quick demonstration), while snes9x works like a charm!

Any idea what's causing such a performance letdown?

**Comment by deltabeard** [comment]
I've just tested Chrono Trigger with the latest commit of Snes9x2010. It's running at full speed and there is no clicking. Would you be able to retest your game?
