### ISSUE TITLE
No way to disable log messages

### ISSUE THREAD

**Issue by unixpickle** [libretro/snes9x2010#102]
The code is littered with `printf` statements that cannot be suppressed. APIs should never uncontrollably print to the console, and *especially* not to stdout. I propose adding `#ifdef SNES_SILENT`s around the logs to optionally disable logging. If I made a PR for this, would it be accepted? If not, is there a better way to do this?

**Comment by hizzlekizzle** [comment]
should be fixed now with #130 so I'm going to close this. We'll reopen if not.
