### ISSUE TITLE
how to build this source?

### ISSUE THREAD

**Issue by kikyo2006** [libretro/snes9x2010#103]
Hello, i don't know how to build this source. After i'm build with command
`make`
then i'm getting errors with next command:
```
make install
make: *** No rule to make target 'install'.  Stop.
```
Can anyone give me step to build and install it?

**Comment by LodanZark** [comment]
You already have the majority of cores compiled through the build bot: http://bot.libretro.com/nightly/
If you want to compile it for the retropie, you have to use their script: https://github.com/RetroPie/RetroPie-Setup/wiki/Manual-Installation

**Comment by hizzlekizzle** [comment]
you should use:
make -f Makefile.libretro

**Comment by kikyo2006** [comment]
Thank you :)
