### ISSUE TITLE
Increase SRAM size

### ISSUE THREAD

**Issue by cout** [libretro/snes9x2010#147]
For save states to work in the Super Metroid practice hack, SRAM size needs to be increased to 0x80000.  This change has already been made in snes9x and has been working well (https://github.com/snes9xgit/snes9x/issues/637).  In snes9x accessing SRAM beyond $71FFFF was causing undefined behavior due to lack of bounds checking; at a glance, it looks like the same problem exists in snes9x2010.  Increasing SRAM size eliminates the UB without requiring bounds checking.

**Comment by twinaphex** [comment]
Alright, if it has no negative consequences I'd be fine with merging any PR that gets sent our way.

**Comment by cout** [comment]
Sounds good, I'll try to get a PR together this week.
