### ISSUE TITLE
1:1 PAR aspect ratio shows non-square pixels

### ISSUE THREAD

**Issue by ghost** [libretro/snes9x2010#27]
Using the parameters "Aspect Ratio: 256:239 (1:1 PAR)" and "Integer Scale: ON" still display non-square pixels.
This is very noticable and looks very bad.

Here is a screenshot taken by RetroArch followed by a screenshot of how the game displays on my screen.
![gpuscreenshot](https://f.cloud.github.com/assets/5928514/2004936/901c62fc-86c9-11e3-814d-5df665843ac0.png)
![screenshot](https://f.cloud.github.com/assets/5928514/2004937/949075e4-86c9-11e3-870f-dd9dd2b313f1.png)

I'm using the latest git of this core as well as the latest git of RetroArch on ArchLinux x86_64.

**Comment by KitchUK** [comment]
I think crop overscan on fixes this. Shouldn't it be the other way around and off should be correct?

**Comment by hizzlekizzle** [comment]
should be fixed now with #130 so I'm going to close this. We'll reopen if not.
