### ISSUE TITLE
missing compile instructions

### ISSUE THREAD

**Issue by GM-Script-Writer-62850** [libretro/snes9x2010#36]
I would like to compile this so i can try the [multitap patch](/libretro/snes9x-next/commit/c701a1e4357bc80e46cae5bdfa0d359bcbce23ad) out, but i cant find any instructions on how to do so
*running 64bit xubuntu

**Comment by meepingsnesroms** [comment]
In terminal:
cd *(parent dir)/libretro-snes9x2010
make
