### ISSUE TITLE
(all platforms) HDMA in games is not correctly displayed

### ISSUE THREAD

**Issue by netux79** [libretro/snes9x2010#58]
Games that uses HDMA are not correctly displayed, it is more likely that HDMA is not working at all (turned off). I tested the same on snes9x core and CatSFC core and HDMA is displayed correctly. I test some older version and same behaviour. Not sure if it is a know issue.

**Comment by meepingsnesroms** [comment]
Tested with chrono trigger (hdma menu gradients),and theirs a gradient so this seems fixed.
