### ISSUE TITLE
StarFox 2 (Final Beta) dont load

### ISSUE THREAD

**Issue by RaZer0k** [libretro/snes9x2010#71]
i test some starfox 2 beta version, but the emulator dont load the game... but snes9x of windows load ok

**Comment by RobLoach** [comment]
What CRC are you on? `79f3433d` seemed to work with:

```
retroarch -L ~/.config/retroarch/cores/snes9x_next_libretro.so starfox2.sfc
```

Strangely, it doesn't list the rom in the RetroArch UI.

**Comment by meepingsnesroms** [comment]
Mine worked too with crc32 96d743e4.
