### ISSUE TITLE
Save state files being created as SNES.state, rather than [rom_name].state

### ISSUE THREAD

**Issue by brotherbean** [libretro/snes9x2010#83]
Emulation is working like a charm, except for saves.  I'd expect save states to be created as [rom_name].state where there would be a separate save state file for each rom, but instead it seems to be creating a single SNES.state file that is being shared and overwritten by each rom.  This is also happening with in-game save .srm files as well (SNES.srm instead of [rom_name].srm).  

Verified that other system emulators are able to create save state files as expected, this seems to be limited to only the SNES.  Any insight would be appreciated.

**Comment by fr500** [comment]
On what platform?

**Comment by brotherbean** [comment]
Sorry, Retropie, latest.

**Comment by fr500** [comment]
We don't really offer support for retropie issues.
I just tried in vanilla retroarch windows and emscripten and the saves are
named correctly

**Comment by meepingsnesroms** [comment]
This is a retropi issue not a core issue.
