### ISSUE TITLE
Star fox runs too fast

### ISSUE THREAD

**Issue by lostless** [libretro/snes9x2010#86]
Star fox in game play is running too fast compared to the original game. Audio plays correctly.  Good example is the into when the ships are flying out of the hanger, a voice says prepare for launch and the ships then fly out.  In snes9x2010,  the game just cuts off the voice cause the games in game engine is running too fast.

**Comment by meepingsnesroms** [comment]
This also happens when using snes9x(latest) with superfx over clock enabled.
So the game is using the superfx as a timer and s9x 2010 doesn't throttle the superfx even with over clock disabled.

I do not know why this is,if you do please state it.
(If you don't know how to program but think you know why please post also.)

**Comment by lostless** [comment]
Researching and found that star fox looks like it bases its speed off the clock of the super fx chip.  There are videos of people that put the rom onto doom super fx2 board and star fox runs just like the emulator.  Too fast.  Seems to me that the super fx driver in snes9x2010 was programmed as a super fx 2 chip. The newer super fx code in snes9x, couldbe backported,  but don't know if that's possible and if so, how that would effect performace on low power devices.  
I'm no programmer, but I do dabble in electronics.

**Comment by meepingsnesroms** [comment]
Then why does setting SFX under clock to 5mhz not fix it.(since the superfx 2 is 2 times as fast just halfing the clock rate would fix it)

**Comment by lostless** [comment]
Beyond my knowlede

**Comment by meepingsnesroms** [comment]
Fixed
(there was a || where there needed to be a &&)
