### ISSUE TITLE
User device type not being reloaded

### ISSUE THREAD

**Issue by Jzooor** [libretro/snes9x2010#91]
I am running Snes9x 2010 1.52.4 7d25113 on an RPI3. Playing games that use the SNES Mouse (my daughter likes Mario Paint and the Mario Early Years games), I can switch the user device type in the quick menu controls menu to SNES Mouse and the mouse works properly. However if I save a game remap file and exit/restart the ROM, the setting will have gone back to SNES Joypad and not reload my mouse selection.

This worked properly back when the core was still snes9x-next.

**Comment by Jzooor** [comment]
To clarify, the device type is being saved in the remap file, but not reloaded when starting the ROM.
I checked in the file and the line "input_libretro_device_p1 = "2"" is present. Trying to load the game remap file manually from the quick menu does nothing to update the selected device type either.

**Comment by fr500** [comment]
uh...
remaps doesn't store the device type

**Comment by Jzooor** [comment]
So what is "input_libretro_device_p1" in the remap file for then?

**Comment by fr500** [comment]
You should be running a really old build. Those paremeters aren't being added and that hasn't been the case for a while. 

The parameter could still be there from an old nightly experiment or something.

**Comment by Jzooor** [comment]
The remap files may have been created while the core was snes9x-next, so
perhaps somewhere along the line there was a regression and that feature
was lost.

**Comment by fr500** [comment]
It was a test, not really a feature. I plan on adding that again but with separate flags from the main cfg

**Comment by Jzooor** [comment]
Well it was extremely useful to me, can you point me toward which commit removed it?

**Comment by fr500** [comment]
no idea more than a year ago

**Comment by Jzooor** [comment]
Ah, I see where it was done upstream in retroarch. Added in Feb (67a68c0), removed in Nov (281aa1d). 

It was incredibly useful; saved me from having to change settings when my kid wanted to play and kept me from having to describe how to do it to the wife when I'm not around. 

I'll see if I can manage to use some rom specific config files to apply the setting.
