### ISSUE TITLE
Cannot exit from the following Error message in snes9x_next: "Please Note: If you are using a mouse, superscope, or multiplayer adapter, then switch to controller. Thanks!."

### ISSUE THREAD

**Issue by webodan** [libretro/snes9x2010#93]
Whenever I run certain SNES ROMs i get a message along the lines of the title.

I searched through the input options to make sure whether there was any of those controllers set instead of SNES Joypad but I didn't see any mentions of them in any of the settings.

The game does run in other cores but the transparency for the trees in certain stages is not well implemented and I can't see what i'm doing, so I wanted to try this one core since it's the most accurate, but I can't because of this screen I can't get out of. I'm sorry if this doesn't belong but I just don't know where to report this.

I hope someone can help me.

**Comment by meepingsnesroms** [comment]
Controller 1 and 2 should be set to "SNES Joypad" and everything else should be set to "None".

Is your configuration different then that, setting any controller above 2 to anything, automatically enables the multitap which the game says is unsupported.

Also what game are you playing?
