### ISSUE TITLE
Hook (USA) has some serious artifact issues

### ISSUE THREAD

**Issue by nikkoman** [libretro/snes9x2010#97]
It doesn't seem that this has been reported anywhere. Hook (USA).sfc seems to have some serious artifact issues in (RPi 3) lr-Snes9x 2010 so I'll be loading it with Snes9x 2005 for now, with inferior sound.

I tried several versions of Snes9x for Windows (including builds from around 2010) and there isn't such an issue. I have also submitted this on retropie.org (just in case someone notices first).

**Comment by OV2** [comment]
This happens if invalid vram access is allowed. S9x2010 has it set to disabled, but one of the speed optimizations causes it to not take effect completely. I'll see if I can commit a fix.
