### ISSUE TITLE
Star Fox 2 final runs slow

### ISSUE THREAD

**Issue by lostless** [libretro/snes9x2010#98]
I’m going say this is a issue but non issue as this only applies to low power devices like the pi.  The beta runs perfect on a pi3 in snes9x2010 but the final build runs with some slowdown.  I don’t know if there were some optimization that made the beta run optimally that are not being picked up when loading the final build.  If not and this is just the way it is that’s fine

**Comment by LodanZark** [comment]
You can try change the overclock settings to see if it improves the experience:
https://github.com/libretro/snes9x2010/blob/77e2c9822bc538045cbf6fcdd71fc31152654b3c/libretro/libretro.c#L372

**Comment by lostless** [comment]
didn't make any difference. The audio is still choppy and gameplay is a tad slow. The rom runs fine on my computer and It's the only game that has issues with the pi.  The final beta ran pertly and if the Pi  can't run it at full speed, then so be it.  Thats why I say its a non issue, its not a problem with the emulator itself but a optimization issue with a lower power device.

**Comment by LodanZark** [comment]
I tested in the RPi3 and works fine with 80MHz overclock. which model you're using ?

**Comment by lostless** [comment]
Im using a Pi3, not overclocked.  The super fx overclock setting seems to make no difference to me.  The game runs fine, just has slowdown.  Listen to how the audio chops up in the intro. If you're  running the old beta, it runs fine without issue.  Im talking about the final build from the snes classic, which makes me think (and may be wrong) that there was some optimization done to the beta rom that is not being used when running the final build. They can't be that different, can they?

**Comment by dankcushions** [comment]
yoshi's island (another super fx 2 game) also slows down on a pi3 on later levels. it's just more than the pi's very weak CPU can handle.

**Comment by nikkoman** [comment]
It's not related to Pi's CPU. The beta hack (which is extremely close to what Nintendo revealed as final in the new ROM) runs fine. The newly extracted ROM plays sluggishly with lots of sound "pops" from the beginning. In my opinion, the emulator has not been optimised for the ROM, since we're talking about a new title.

**Comment by Oggom** [comment]
https://github.com/libretro/snes9x2010/pull/100 should fix this. The SNES Classic version has a different header than the beta and therefore the speed hack wasn't being applied.

**Comment by lostless** [comment]
Tested.  Fixed  Thank you
